const weapons = [
  { name: "None",
    air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0,
    defense: { air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 }
  },
  { name: "Altadorian Swordbreaker", air: 0, dark: 0, earth: 5, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Amulet of Altador", air: 3, dark: 0, earth: 0, fire: 0, light: 3, water: 0, physical: 0 },
  { name: "Amulet of Inevitable Betrayal", air: 2, dark: 2, earth: 0, fire: 0, light: 0, water: 3, physical: 0 },
  { name: "Amulet of the Unblinking Eye", air: 0, dark: 3, earth: 0, fire: 3, light: 3, water: 0, physical: 0 },
  { name: "Ancient Gnarled Wand", air: 3, dark: 3, earth: 2, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Ancient Repeating Crossbow", air: 3, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 2 },
  { name: "Asparagus Dagger", air: 0, dark: 0, earth: 3, fire: 0, light: 3, water: 0, physical: 0.3 },
  { name: "Battle Faerie Dual Swords", air: 2, dark: 0, earth: 0, fire: 3, light: 0, water: 0, physical: 3 },
  { name: "Bleached Bone Staff", air: 0, dark: 0, earth: 5, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Blue Acara Bow", air: 3, dark: 0, earth: 0, fire: 1, light: 2, water: 0, physical: 2 },
  { name: "Blunted Qasalan Gladius Sword", air: 3, dark: 0, earth: 2, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Bottled Volcano Steam", air: 0, dark: 0, earth: 0, fire: 3, light: 2, water: 3, physical: 0 },
  { name: "Bow of the Hegelob", air: 0, dark: 0, earth: 3, fire: 3, light: 0, water: 3, physical: 0 },
  { name: "Bubble Wands", air: 3, dark: 0, earth: 0, fire: 0, light: 3, water: 3, physical: 0 },
  { name: "Carved Qasalan Blowgun", air: 0, dark: 0, earth: 3, fire: 3, light: 0, water: 3, physical: 0 },
  { name: "Carved Sansetsukon", air: 0, dark: 0, earth: 2, fire: 0, light: 2, water: 0, physical: 3 },
  { name: "Celestial Scroll", air: 4, dark: 0, earth: 2, fire: 0, light: 2, water: 0, physical: 0 },
  { name: "Chain Spear", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 6 },
  { name: "Chia Ray Gun", air: 0, dark: 0, earth: 0, fire: 3, light: 5, water: 0, physical: 0 },
  { name: "Chilli Sword", air: 0, dark: 0, earth: 0, fire: 8, light: 0, water: 0, physical: 0 },
  { name: "Claw of the Ancient Bori", air: 0, dark: 0, earth: 5, fire: 0, light: 0, water: 3, physical: 0 },
  { name: "Cloudy Wand of Storms", air: 0, dark: 2.6, earth: 0, fire: 2.6, light: 0, water: 2, physical: 0 },
  { name: "Cobrall Cannon", air: 0, dark: 0, earth: 0, fire: 6, light: 0, water: 0, physical: 2 },
  { name: "Commander Blade", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 2, physical: 5 },
  { name: "Cooty Crossbow", air: 3, dark: 3, earth: 0, fire: 0, light: 0, water: 3, physical: 0 },
  { name: "Dangerous Dodgeball", air: 0, dark: 7, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Darigan Generals Sword", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 7 },
  { name: "Dark Battle Duck", air: 0, dark: 3, earth: 0, fire: 0, light: 0, water: 5, physical: 0 },
  { name: "Dark Longblade Axe", air: 2, dark: 3, earth: 3, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Deadly Pugio", air: 0, dark: 0, earth: 2, fire: 2, light: 0, water: 0, physical: 0.5 },
  { name: "Decorative Maractite Sword", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 5, physical: 3 },
  { name: "Desert Crossbow", air: 0, dark: 0, earth: 0, fire: 6, light: 2, water: 0, physical: 0 },
  { name: "Devious Top Hat and Cat", air: 2, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 2 },
  { name: "Dry Ice Snowball", air: 6, dark: 0, earth: 0, fire: 0, light: 0, water: 3, physical: 0 },
  { name: "Dual Batons of Katsuo", air: 0, dark: 2, earth: 3, fire: 2, light: 0, water: 0, physical: 2 },
  { name: "Dusty Magic Broom", air: 3, dark: 0, earth: 5, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Earth Scarab", air: 0, dark: 0, earth: 5, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Electro Sword", air: 0, dark: 0, earth: 0, fire: 3, light: 3, water: 0, physical: 2 },
  { name: "Elegant Desert Sword", air: 2, dark: 0, earth: 2, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Elephante Sword", air: 0, dark: 0, earth: 2, fire: 0, light: 0, water: 3, physical: 2 },
  { name: "Essence of Esophagor", air: 0, dark: 0, earth: 4.5, fire: 0, light: 0, water: 4.5, physical: 0 },
  { name: "Exceptionally Tiny Laser Cannon", air: 0, dark: 0, earth: 3, fire: 0, light: 3, water: 2, physical: 0 },
  { name: "Faerie Pteri Chakram", air: 2, dark: 0, earth: 0, fire: 0, light: 3, water: 0, physical: 3 },
  { name: "Faerie Shield", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Festive Cutlass", air: 0, dark: 3, earth: 0, fire: 5, light: 0, water: 0, physical: 0 },
  { name: "Festive Holiday Scroll", air: 3, dark: 0, earth: 0, fire: 0, light: 3, water: 0, physical: 3 },
  { name: "Fiery Throwing Marble", air: 3, dark: 0, earth: 0, fire: 3, light: 0, water: 0, physical: 2 },
  { name: "Fighting Folder", air: 0, dark: 0, earth: 2, fire: 3, light: 0, water: 0, physical: 0.3 },
  { name: "Flaming Log Launcher", air: 0, dark: 0, earth: 2, fire: 3, light: 0, water: 0, physical: 3 },
  { name: "Flaming Toaster", air: 2, dark: 0, earth: 0, fire: 2, light: 2, water: 0, physical: 2 },
  { name: "Florins Flask", air: 0, dark: 0, earth: 5, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Flotsam Ice Shell", air: 3, dark: 0, earth: 0, fire: 0, light: 0, water: 3, physical: 0 },
  { name: "Frozen Cyodrake Shield", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Frozen Ogrin Mane", air: 2, dark: 0, earth: 0, fire: 0, light: 0, water: 2, physical: 3 },
  { name: "Frozen Scarf Whip", air: 2, dark: 0, earth: 0, fire: 0, light: 0, water: 3, physical: 3 },
  { name: "Frozen Water Daggers", air: 2, dark: 0, earth: 3, fire: 0, light: 0, water: 3, physical: 0 },
  { name: "Frozen Wave Scimitar", air: 3, dark: 0, earth: 0, fire: 0, light: 0, water: 3, physical: 2 },
  { name: "Full Buzz Armour", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Ghostly Jetsam Sword", air: 0, dark: 2, earth: 0, fire: 0, light: 0, water: 2, physical: 3 },
  { name: "Gilded War Hammer", air: 2, dark: 0, earth: 0, fire: 0, light: 3, water: 0, physical: 3 },
  { name: "Glaive of Verdancy", air: 3, dark: 0, earth: 5, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Gleaming Qasalan Crossbow", air: 0, dark: 0, earth: 2, fire: 2, light: 2, water: 0, physical: 2 },
  { name: "Gold Handheld Katana", air: 0, dark: 0, earth: 3, fire: 2, light: 0, water: 0, physical: 3 },
  { name: "Golden Bori Bow", air: 3, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 2 },
  { name: "Golden Candy Cane Sword", air: 0, dark: 0, earth: 0, fire: 2, light: 3, water: 0, physical: 3 },
  { name: "Golden Coin Amulet", air: 0, dark: 2, earth: 0, fire: 0, light: 3, water: 0, physical: 0 },
  { name: "Golden Compass", air: 3, dark: 0, earth: 0, fire: 3, light: 3, water: 0, physical: 0 },
  { name: "Golden Geraptiku Talisman", air: 0, dark: 3, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Greater Air Potion", air: 7, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Greater Orb of the Fire Faerie", air: 0, dark: 0, earth: 0, fire: 7, light: 0, water: 0, physical: 0 },
  { name: "Greater Water Potion", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 7, physical: 0 },
  { name: "Grimoire of Thade", air: 0, dark: 5, earth: 0, fire: 0, light: 0, water: 0, physical: 0.3 },
  { name: "Hand Carved Blumaroo Bow", air: 3, dark: 0, earth: 2, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Hansos Masamune", air: 3, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 5 },
  { name: "Haunted Skull Fan", air: 6, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Holiday Light String Lasso", air: 3, dark: 0, earth: 2, fire: 0, light: 3, water: 0, physical: 0 },
  { name: "Ice Club", air: 3, dark: 0, earth: 0, fire: 0, light: 0, water: 3, physical: 3 },
  { name: "Ice Dagger", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 3, physical: 0.3 },
  { name: "Icy Bruce Boomerang of Doom", air: 2, dark: 0, earth: 0, fire: 0, light: 3, water: 3, physical: 0 },
  { name: "Iron Lupe Sword", air: 2, dark: 0, earth: 0, fire: 3, light: 0, water: 0, physical: 3 },
  { name: "Island Mystics Staff", air: 5, dark: 3, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Jhudoras Cursed Sword", air: 2, dark: 3, earth: 0, fire: 0, light: 0, water: 2, physical: 0 },
  { name: "Jhudoras Vile Vial", air: 0, dark: 45721, earth: 0, fire: 0, light: 0, water: 45721, physical: 0 },
  { name: "Jhudoras Wand", air: 0, dark: 5, earth: 3, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Jittery Jipple Pear Potion", air: 3, dark: 3, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Kaylas Magic Cloak", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Kazeriu Whip", air: 5, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Kiko Battle Legs", air: 0, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Kiko Skull Pirate Hat", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Kikovision Goggles", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 6, physical: 0 },
  { name: "Korbat Power Blaster", air: 5, dark: 0, earth: 0, fire: 0, light: 0, water: 3, physical: 0 },
  { name: "Leaf Shield", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Lightweight Black Tunic", air: 0, dark: 0-5, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Makeshift Ships Hammer", air: 2, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Meepapault", air: 0, dark: 3, earth: 3, fire: 3, light: 0, water: 0, physical: 0 },
  { name: "Meerca Speed Potion", air: 3, dark: 2, earth: 0, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Meerca Tail Whip", air: 2, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Merciless Idiom", air: 3, dark: 3, earth: 0, fire: 0, light: 3, water: 0, physical: 0 },
  { name: "Moehog Eye Guards", air: 0, dark: 0, earth: 0, fire: 5, light: 0, water: 0, physical: 0 },
  { name: "Mushroom Mace", air: 3, dark: 0, earth: 2, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Mysterious Amulet", air: 0, dark: 3, earth: 0, fire: 3, light: 3, water: 0, physical: 0 },
  { name: "Mystery Fruit Bowl", air: 0, dark: 0, earth: 3, fire: 0, light: 3, water: 0, physical: 3 },
  { name: "Nebula Force Field Generator", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Night Katana", air: 2, dark: 3, earth: 0, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Nightspeed Mace", air: 0, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 2 },
  { name: "Nightsteed Mace", air: 0, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 2 },
  { name: "Oversized Maractite Rune Sword", air: 0, dark: 0, earth: 0, fire: 0, light: 2, water: 3, physical: 2 },
  { name: "Parasol of Unfortunate Demise", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Parchment Cloak", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Phial of the Dreamer", air: 5, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Pickle Spear", air: 0, dark: 0, earth: 8, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Pike Pike", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 4.5, physical: 4.5 },
  { name: "Pirate Captains Hat", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Plush Gelert Collar", air: 0, dark: 0, earth: 0, fire: 3, light: 0, water: 3, physical: 0 },
  { name: "Poisonous Flower", air: 0, dark: 3, earth: 0, fire: 2, light: 0, water: 0, physical: 3 },
  { name: "Psellias Fighting Fan", air: 3, dark: 0, earth: 0, fire: 0, light: 3, water: 0, physical: 3 },
  { name: "Pumpkin Launcher", air: 0, dark: 0, earth: 3, fire: 0, light: 2, water: 0, physical: 3 },
  { name: "Pumpkin Stick", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 8, physical: 0 },
  { name: "Pyon Stinger Mace", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 3, physical: 3 },
  { name: "Rainbow Scroll", air: 3, dark: 0, earth: 0, fire: 0, light: 3, water: 3, physical: 0 },
  { name: "Ramtors Spellbook", air: 0, dark: 5, earth: 0, fire: 0, light: 0, water: 5, physical: 0 },
  { name: "Ridiculously Heavy Battle Hammer", air: 3, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Royal Blue Cape", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Rusty Lamppost", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 5, physical: 0 },
  { name: "Scarab Ring", air: 0, dark: 2, earth: 0, fire: 0, light: 2, water: 0, physical: 2 },
  { name: "Scroll of Forgotten Promises", air: 3, dark: 2, earth: 3, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Scroll of the Battlefield", air: 3, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 6 },
  { name: "Scroll of Virtue", air: 3, dark: 0, earth: 2, fire: 0, light: 2, water: 0, physical: 0 },
  { name: "Scuzzys Comb", air: 0, dark: 0, earth: 0, fire: 0, light: 5, water: 0, physical: 5 },
  { name: "Seti Hilt Sword", air: 3, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 0.3 },
  { name: "Shield of Faerieland", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Shield of Pion Troect", air: 0, dark: 2.49, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Snowager Sword", air: 2, dark: 0, earth: 0, fire: 0, light: 0, water: 2, physical: 3 },
  { name: "Snowflake Pendant", air: 0, dark: 3, earth: 3, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Solar Flare Shield", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Sophies Elixir", air: 0, dark: 2, earth: 3, fire: 0, light: 0, water: 3, physical: 0 },
  { name: "Sophies Magic Hat", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Sophies Wooden Spoon", air: 0, dark: 0, earth: 6, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Spearmint", air: 3, dark: 0, earth: 5, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Spiked Negg Mace", air: 0, dark: 0, earth: 5, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Staff of Devilish Laughter", air: 8, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Stone Club", air: 3, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Strange Marking Stone Necklace", air: 3, dark: 0, earth: 3, fire: 0, light: 3, water: 0, physical: 0 },
  { name: "Sunblade Replica", air: 0, dark: 0, earth: 0, fire: 3, light: 0, water: 0, physical: 0.3 },
  { name: "Sword of the Dead", air: 3, dark: 3, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "The Mystical Tablet", air: 3, dark: 3, earth: 0, fire: 0, light: 3, water: 0, physical: 0 },
  { name: "Throwing Cutlass", air: 3, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Tower Shield", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Tuskaninny Battle Trumpet", air: 3, dark: 0, earth: 5, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Twisted Dark Dagger", air: 0, dark: 3, earth: 2, fire: 0, light: 0, water: 0, physical: 0.3 },
  { name: "Tyrannian Army Math Tools", air: 2.7, dark: 0, earth: 0, fire: 0, light: 0, water: 4.5, physical: 0 },
  { name: "Ugga Loaf of Meat", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Ultimate Battle Yoyo", air: 3, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 2 },
  { name: "Ultimate Negg Hammer", air: 3, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 5 },
  { name: "Ultra Supreme Kiko Walker", air: 0, dark: 0, earth: 0, fire: 0, light: 2.65, water: 0, physical: 2.65 },
  { name: "Umbrella Shield", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Virtupets X-514 Super Shield", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Void Dagger", air: 2, dark: 3, earth: 0, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Wand of Lameness", air: 3, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Wanderers Cloak", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Water Bazooka", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 4, physical: 4 },
  { name: "Wheel Shield", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Whirling Mopper", air: 6, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 3 },
  { name: "Yooyuball Keepers Chest Guard", air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 0 },
  { name: "Zapatron 4000", air: 0, dark: 0, earth: 3, fire: 0, light: 6, water: 0, physical: 0 },
  { name: "Zombie Fist on a Stick",
    air: 0, dark: 0, earth: 3, fire: 0, light: 0, water: 0, physical: 3,
    defense: { air: 0, dark: 0, earth: 0, fire: 0, light: 0, water: 0, physical: 5 }
  },
];